services:
  ms-kafka-consumer:
    image: openjdk:21-slim
    volumes:
      - ./target/ms-kafka-consumer.jar:/app.jar
    container_name: ms-kafka-consumer
    hostname: ms-kafka-consumer
    command: >
      java -Dcom.sun.management.jmxremote=true
      -Dcom.sun.management.jmxremote.port=10483
      -Dcom.sun.management.jmxremote.rmi.port=10484
      -Dcom.sun.management.jmxremote.ssl=false
      -Dcom.sun.management.jmxremote.authenticate=false
      -Djava.rmi.server.hostname=0.0.0.0
      -Dbr.com.eventhorizon.mywallet.ms.kafka.consumer.service.start-delay=0
      -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1g -Xms1g -jar /app.jar
    environment:
      MY_CUSTOM_ENV: "my-custom-value"
    ports:
      - '10487:10484'
      - '5008:5005'
    networks:
      - my-wallet_local-net

networks:
  my-wallet_local-net:
    external: true
